POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2012,
    "mileage": 100000,
    "price": 10000,
    "lat": 37.7749,
    "lng": 122.4194
}